Learning-Logs/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

Learning-Logs/learning_logs/urls.py
from django.urls import path
from . import views

app_name = 'learning_logs'

urlpatterns = [
    path('',views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),

    #Page for editing an entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

Learning-Logs/users/urls.py
from django.urls import path, include

app_name ='users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
]

Learning-Logs/learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        return f"{self.text[:50]}..."

Learning-Logs/users/models.py
from django.db import models

# Create your models here.

Learning-Logs/learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

Learning-Logs/learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.
def index(request):
    return render(request, 'learning_logs/index.html')

def topics(request):
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')
    
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    
    context = {'entry':entry, 'topic':topic, 'form':form}
    return render(request, 'learning_logs/edit_entry.html', context)

Learning-Logs/users/views.py
from django.shortcuts import render

# Create your views here.

Learning-Logs/learning_logs/templates/learning_logs/base.html
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a>
    <a href="{% url 'learning_logs:topics' %}">Topics</a>
    {% if user.is_authenticated %}
        Hello, {{user.username}}
        <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
        <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>
{% block content%}
{% endblock content%}

Learning-Logs/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <p><a href="{% url 'learning_logs:topic' topic.id%}">{{topic}}</a></p>
    <p>Edit entry:</p>
    <form action="{% url 'learning_logs:edit_entry' entry.id%}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button name="submit">Save changes</button>
    </form>

{% endblock content %}

Learning-Logs/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block content%}
<p>Learning Log</p>

<p>Learning Log helps you keep track of your learning, for any topic
    you're learning about.
</p>
{% endblock content%}

Learning-Logs/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <p><a href="{% url 'learning_logs:topic' topic.id%}">{{topic}}</a></p>
    <p>Add a new entry:</p>
    <form action="{% url 'learning_logs:new_entry' topic.id%}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button name="submit">Add entry</button>
    </form>

{% endblock content %}

Learning-Logs/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <p>Add a new topic: </p>
    <form action="{% url 'learning_logs:new_topic' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button name="submit">Add topic</button>
    </form>

{% endblock content %}

Learning-Logs/learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}
{% block content%}
<p>Topic: {{topic}}</p>
<p>Entries: </p>
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
</p>
<ul>
    {% for entry in entries %}
        <li>
            <p>{{entry.date_added|date:'M d, Y h:i'}}</p>
            <p>{{entry.text|linebreaks}}</p>
            <p>
                <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>
            </p>
        </li>
    {% empty %}
        <li>There are no entries for this topic yet.</li>
    {% endfor %}
</ul>
{% endblock content%}

Learning-Logs/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block content%}
<p>Topics</p>

<ul>
    {% for topic in topics %}
        <li>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
        </li>
    {% empty %}
        <li>No topics have been added yet.</li>
    {% endfor %}
</ul>
<a href="{% url 'learning_logs:new_topic'%}">Add a new topic</a>
{% endblock content%}